# Generated by Django 3.2.6 on 2021-12-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='padi',
            new_name='paid',
        ),
    ]
